import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/app.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { UserContext } from "@/context/UserContext";
import { Toaster } from "react-hot-toast";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>GameShop</title>
      </Head>
      <UserContext>
        <Toaster />
        <Component {...pageProps} />
      </UserContext>
    </>
  );
}
